# Generated by Django 5.2.5 on 2025-08-12 15:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_client_managers_alter_client_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='last login'),
        ),
    ]
