# Generated by Django 5.2.5 on 2025-08-12 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_client_date_joined_alter_client_last_login'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='client',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_admin',
        ),
    ]
