# Generated by Django 5.2.5 on 2025-08-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_alter_client_managers_remove_client_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
