# Generated by Django 5.2.5 on 2025-08-12 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_client_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_login',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2025, 8, 12, 19, 12, 23, 606616, tzinfo=datetime.timezone.utc), verbose_name='last login'),
            preserve_default=False,
        ),
    ]
