# Generated by Django 5.2.5 on 2025-08-12 15:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_delete_exercise_delete_exercisedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='id',
        ),
        migrations.AddField(
            model_name='client',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default='default@email.com', max_length=254, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(default='password123', max_length=128),
        ),
        migrations.AddField(
            model_name='client',
            name='username',
            field=models.CharField(default='name', max_length=100),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='bmi',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='body_fat_pct',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='body_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='calorie_goal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='injuries',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='intermittent_fasting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='muscle_mass',
            field=models.FloatField(db_default=0.0),
        ),
        migrations.AddField(
            model_name='clientdata',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='feedback',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='feedback',
            name='meal_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.mealplan'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feedback',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.recipe'),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='recipes',
            field=models.ManyToManyField(to='client.recipe'),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='shopping_list',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='metric',
            name='blood_pressures',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='metric',
            name='calorie_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metric',
            name='calorie_intake',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metric',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
        migrations.AddField(
            model_name='metric',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='metric',
            name='heart_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metric',
            name='intermittent_fasting_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metric',
            name='intermittent_fasting_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='metric',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='metric',
            name='mood',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='metric',
            name='sleep',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='metric',
            name='stress_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metric',
            name='weekly_goal_status',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='recipe',
            name='api_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='dietary_preferences',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='week_goals_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='week_goals_mind',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='week_goals_soul',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
    ]
