# Generated by Django 5.2.5 on 2025-08-12 15:55

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_client_options_alter_client_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='client',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(default='', max_length=254, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
