# Generated by Django 5.2.5 on 2025-08-12 19:57

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('major_muscle', models.CharField(choices=[('ABDUCTORS', 'abductors'), ('ABS', 'abs'), ('ADDUCTORS', 'adductors'), ('BICEPS', 'biceps'), ('CALVES', 'calves'), ('CARDIOVASCULAR SYSTEM', 'cardiovascular system'), ('DELTS', 'delts'), ('FOREARMS', 'forearms'), ('GLUTES', 'glutes'), ('HAMSTRINGS', 'hamstrings'), ('LATS', 'lats'), ('LEVATOR SCAPULAE', 'levator scapulae'), ('PECTORALS', 'pectorals'), ('QUADS', 'quads'), ('SERRATUS ANTERIOR', 'serratus anterior'), ('SPINE', 'spine'), ('TRAPS', 'traps'), ('TRICEPS', 'triceps'), ('UPPER BACK', 'upper back')], max_length=100)),
                ('minor_muscle', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('exercise_category', models.CharField(max_length=50)),
                ('target_body_part', models.CharField(choices=[('BACK', 'back'), ('CARDIO', 'cardio'), ('CHEST', 'chest'), ('LOWER_ARMS', 'lower arms'), ('LOWER_LEGS', 'lower legs'), ('NECK', 'neck'), ('SHOULDERS', 'shoulders'), ('UPPER_ARMS', 'upper arms'), ('UPPER_LEGS', 'upper legs'), ('WAIST', 'waist')], max_length=50)),
                ('equipment', models.CharField(max_length=50)),
                ('instructions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('description', models.CharField(max_length=150)),
                ('exercise_level', models.CharField(max_length=50)),
                ('calorie_burn', models.FloatField(default=0.0)),
                ('score', models.IntegerField()),
                ('external_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration', models.FloatField()),
                ('distance', models.FloatField()),
                ('repetition', models.IntegerField()),
                ('set', models.IntegerField()),
                ('exercise_category', models.CharField(max_length=50)),
                ('exercise_type', models.CharField(max_length=50)),
                ('exercise_level_rate', models.IntegerField()),
                ('excercise_heart_rate', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise', to_field='name')),
            ],
        ),
    ]
